import type { CurrencyCode } from "@sage/core";

const EXCHANGE_TO_CURRENCY: Record<string, CurrencyCode> = {
  NMS: "USD",
  NGM: "USD",
  NCM: "USD",
  NYQ: "USD",
  PCX: "USD",
  BTS: "USD",
  ASE: "USD",
  OPR: "USD",
  LSE: "GBP",
  IOB: "GBP",
  GER: "EUR",
  FRA: "EUR",
  PAR: "EUR",
  AMS: "EUR",
  BRU: "EUR",
  MIL: "EUR",
  MAD: "EUR",
  ATH: "EUR",
  HEL: "EUR",
  LIS: "EUR",
  VIE: "EUR",
  DUS: "EUR",
  HAM: "EUR",
  MUN: "EUR",
  STU: "EUR",
  CPH: "DKK",
  STO: "SEK",
  OSL: "NOK",
  TOR: "CAD",
  CNQ: "CAD",
  NEO: "CAD",
  EBS: "CHF",
  JPX: "JPY",
  TYO: "JPY",
  HKG: "HKD",
  ASX: "AUD",
  KSC: "KRW",
  KOE: "KRW",
  TAI: "TWD",
  BSE: "INR",
  NSI: "INR",
  SAO: "BRL",
  MEX: "MXN",
  JKT: "IDR",
  SET: "THB",
  NZE: "NZD",
  WSE: "PLN",
  IST: "TRY",
  JNB: "ZAR",
  TAL: "EUR",
  RIS: "EUR",
};

export function exchangeToCurrency(exchange: string): CurrencyCode | undefined {
  return EXCHANGE_TO_CURRENCY[exchange];
}
