const REGION_MAP: Record<string, string> = {
  US: "North America",
  CA: "North America",
  GB: "Europe",
  DE: "Europe",
  FR: "Europe",
  NL: "Europe",
  SE: "Europe",
  DK: "Europe",
  NO: "Europe",
  CH: "Europe",
  IT: "Europe",
  ES: "Europe",
  FI: "Europe",
  BE: "Europe",
  AT: "Europe",
  IE: "Europe",
  PT: "Europe",
  PL: "Europe",
  JP: "Asia-Pacific",
  AU: "Asia-Pacific",
  HK: "Asia-Pacific",
  SG: "Asia-Pacific",
  KR: "Asia-Pacific",
  TW: "Asia-Pacific",
  CN: "Asia-Pacific",
  IN: "Asia-Pacific",
  NZ: "Asia-Pacific",
  BR: "Latin America",
  MX: "Latin America",
  CL: "Latin America",
  AR: "Latin America",
  CO: "Latin America",
  ZA: "Africa",
  NG: "Africa",
  EG: "Africa",
  KE: "Africa",
  SA: "Middle East",
  AE: "Middle East",
  IL: "Middle East",
  QA: "Middle East",
  KW: "Middle East",
};

export function countryToRegion(countryIso: string | null): string {
  if (!countryIso) return "Unknown";
  return REGION_MAP[countryIso.toUpperCase()] ?? "Other";
}
